### ISSUE TITLE
Port mismatch on Windows

### ISSUE THREAD

**Issue by charlietharas** [msk-mind/luna#323]
Ports displayed by the `make run` command do not match up with the actual ports accessible via the browser on Windows. Full list:

- Minio claims to be deployed at port 9500 but is actually at port 60680
- Dremio claims to be deployed at port 9047 but is actually at port 60688
- DSA claims to be deployed at port 8080 but is actually at port 60687
- Jupyter claims to be deployed at port 8888 but is actually at port 60686

These correct ports (right hand side) **regenerate/change** on every run of `make run`.

I was able to find these ports via listing with `netstat -tulpn | grep LISTEN`. There are also a bunch of active ports seemingly opened by Docker that claim to be in use but lead nowhere when accessed via browser (assuming this is normal). 

Once the correct ports are accessed on the browser, they are totally functional.

**Comment by charlietharas** [comment]
https://github.com/microsoft/WSL/issues/5575
https://superuser.com/questions/1469431/cant-open-port-even-there-is-no-other-applications-are-listening-on-it-windows/1671709#1671709
https://github.com/microsoft/WSL/issues/4619
https://docs.microsoft.com/en-us/powershell/module/hyper-v/get-vmcomport?view=windowsserver2022-ps

**Comment by arfathpasha** [comment]
Charlie I think this port forwarding technique could be the solution. If it works, it should be easily scriptable

https://youtu.be/ACjlvzw4bVE

**Comment by charlietharas** [comment]
Doesn't seem to do anything for me, based on what he's describing I think it's more for accessing localhost services on a remote device (since he seems to access his localhost port just fine).

**Comment by charlietharas** [comment]
Seems resolved after latest commits (ignoring #332 which breaks npm dependencies) + checking out from within WSL + updating Docker Desktop.
