### ISSUE TITLE
recommendations for running with singularity?

### ISSUE THREAD

**Issue by andreabc** [msk-mind/luna#349]
Hi, I'm unable to use docker at my institution, I was able to pull the luna image from docker hub with singularity but am running into issues going through the tutorials. Are there any recommendations for running inference through singularity? 

Also, I couldn't find the trained model in the container or GitHub, are those provided anywhere or are we expected to retrain the base model?

Thank you

**Comment by armaank** [comment]
Hi, thanks for reaching out! We're currently working on improving package, documentation and [tutorials](https://msk-mind.github.io/luna/tutorials/4_inference-and-visualization/ ), but we do have documentation on how to run [model inference](https://msk-mind.github.io/luna/cli_reference/pathology/infer_tiles/) with a model pre-trained on HGSOC overian cancer slides pulled from a [torch-hub instance](https://github.com/msk-mind/luna-ml). 

What are you trying to use our package for? Depending on your application you may need to train a model from scratch.

**Comment by andreabc** [comment]
Hi, thanks for your reply! We were hoping to use the NSCLC model from [Vanguri et al](https://www.nature.com/articles/s43018-022-00416-8) to run preliminary inference on some H&E slides we have. However I have just noticed that the pathology slides in the manuscript are IHC stained whereas are are not

**Comment by armaank** [comment]
Hi Andrea, just an FYI in case you're still interested, you can see all of the data and code associated w/ the Vanguri et. al paper here: https://www.synapse.org/#!Synapse:syn26642505/wiki/615361 . But yes, the project uses IHC, not H&E.
