### ISSUE TITLE
About  genomic_inventory_v1_FINAL.csv

### ISSUE THREAD

**Issue by SZ-qing** [msk-mind/luna#391]
Hello, I'm using your code to prepare to reproduce the results of the article, and I see in the `save_table_1A` function on `line 3586` of your `lung_helpers.py` file that it needs to read file **./omnibus/genomic_inventory_v1_FINAL.csv**. May I ask where this you provide the

**Comment by SZ-qing** [comment]
In `Figures-Finalized-Permutation-Test.ipynb` ：
**df_clinical_old = pd.read_csv("/gpfs/mskmindhdp_emc/user/shared_data_folder/lung-mind-project/cohorts/MIND Cohort_v2_8August2020.csv")**
I don't see this file and other files included in this notebook, such as:
lung_helpers.py--->line 407: df = pd.read_csv("/gpfs/mskmind_emc/data_user/aukermaa/LUNG_DATA/id_inventory_v3.csv")

**Comment by armaank** [comment]
Hi - some of those files aren't needed to the final analysis to reproduce results. Please refer to this synapse repository that contains the final data and code for the project: https://www.synapse.org/#!Synapse:syn26642505/wiki/615361

**Comment by SZ-qing** [comment]
In `Figures-Finalized.ipynb` to reproduct the **Fig. 2D Fig. 3E Fig. 4C and Fig. 4D** which need `generate_auc_plot_V2` function. 
but this need results of `get_null_mean_error` function, which is producted by [https://github.com/msk-mind/luna/issues/391#issuecomment-1693026647]

**Comment by armaank** [comment]
Are you looking for access to the permuted data used for the permutation tests? If so, I can add them to the synapse repo.

**Comment by SZ-qing** [comment]
Yes, as above, I need it to repeat the result!

---- Replied Message ----
| From | ***@***.***> |
| Date | 08/30/2023 21:25 |
| To | ***@***.***> |
| Cc | SZ-qing ***@***.***>,
Author ***@***.***> |
| Subject | Re: [msk-mind/luna] About genomic_inventory_v1_FINAL.csv (Issue #391) |

Are you looking for access to the permuted data used for the permutation tests? If so, I can add them to the synapse repo.

**Comment by armaank** [comment]
Hi - I've updated the [synapse page]( https://www.synapse.org/#!Synapse:syn26642505/wiki/615361) accordingly - please see the `tests` folder in the files section

**Comment by SZ-qing** [comment]
Thanks

---- Replied Message ----
| From | ***@***.***> |
| Date | 08/30/2023 21:46 |
| To | ***@***.***> |
| Cc | SZ-qing ***@***.***>,
Author ***@***.***> |
| Subject | Re: [msk-mind/luna] About genomic_inventory_v1_FINAL.csv (Issue #391) |

Hi - I've updated the synapse page accordingly - please see the tests folder in the files section
